### ISSUE TITLE
Failed to update citation style

### ISSUE THREAD

**Issue by Flashtim** [josephwright/biblatex-ieee#56] opened 2020-09-02 14:35 UTC
Since the latest update, using style=ieee produces errors in ieee.cbx when building the file:

`ieee.cbx:48: Package biblatex-ieee Error: Failed to update citation style. [...p,cite:comp:end,cite:comp:inset,cite:dump}]
ieee.cbx:58: Package biblatex-ieee Error: Failed to update citation style. [  }] `

I'm using the recent Miktex version 2.9.

A simple example that won't compile:

```
\documentclass[]{scrreprt}

\PassOptionsToPackage{%
  style=ieee,
}{biblatex}
    \usepackage{biblatex}

\begin{document}
Test
\end{document} 
```

**Comment by Flashtim** [comment] 2020-09-02 14:37
biblatex version: 3.15a
biblatex-ieee version: 1.3b

**Comment by josephwright** [comment] 2020-09-02 14:41
Duplicate of https://github.com/josephwright/biblatex-ieee/issues/55

**Closed by josephwright** 2020-09-02 14:41 UTC
